- hosts: localhost
  vars:
    resource_group: myResourceGroup
    location: eastus
    mysqlserver_name: mysqlserveransible
    mysqldb_name: mysqldbansible
    admin_username: mysqladmin
    admin_password: 4da1sttymevaMU502MC 
  tasks:
    - name: Create MySQL Server
      azure.azcollection.azure_rm_mysqlserver: 
        resource_group: "{{ resource_group }}"
        name: "{{ mysqlserver_name }}"
        sku:
          name: B_Gen5_1
          tier: Basic
        location: "{{ location }}"
        version: 5.7
        enforce_ssl: True
        admin_username: "{{ admin_username }}"
        admin_password: "{{ admin_password }}"
        storage_mb: 51200

    - name: Create instance of MySQL Database
      azure_rm_mysqldatabase: 
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
        name: "{{ mysqldb_name }}"

    - name: Open firewall to access MySQL Server from outside
      azure_rm_resource:
        api_version: '2017-12-01'
        resource_group: "{{ resource_group }}"
        provider: dbformysql
        resource_type: servers
        resource_name: "{{ mysqlserver_name }}"
        subresource:
          - type: firewallrules
            name: externalaccess
        body:
          properties:
            startIpAddress: "0.0.0.0"
            endIpAddress: "255.255.255.255"

