--- 
- 
  hosts: localhost
  tasks: 
    - 
      azure.azcollection.azure_rm_mysqlserver_info: 
        resource_group: "{{ resource_group }}"
      name: "Query MySQL Servers in current resource group"
      register: mysqlserverfacts
    - 
      debug: 
        var: mysqlserverfacts
      name: "Dump MySQL Server facts"
    - 
      azure.azcollection.azure_rm_mysqldatabase_info: 
        resource_group: "{{ resource_group }}"
        server_name: "{{ mysqlserver_name }}"
      name: "Query MySQL Databases"
      register: mysqldatabasefacts
    - 
      debug: 
        var: mysqldatabasefacts
      name: "Dump MySQL Database Facts"
  vars: 
    mysqlserver_name: mysqlserveransible
    resource_group: myResourceGroup
